/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartAngleAxisConfig: typeof import('./../components/chart-config/angle-axis/ChartAngleAxisConfig.vue')['default']
    ChartAnimationConfig: typeof import('./../components/chart-config/animation/ChartAnimationConfig.vue')['default']
    ChartAxisConfig: typeof import('./../components/chart-config/xAxis/ChartAxisConfig.vue')['default']
    ChartBarConfig: typeof import('./../components/chart-config/bar/ChartBarConfig.vue')['default']
    ChartBarPubConfig: typeof import('./../components/chart-config/bar/ChartBarPubConfig.vue')['default']
    ChartBasicLineConfig: typeof import('./../components/chart-config/line/ChartBasicLineConfig.vue')['default']
    ChartGenerateConfig: typeof import('./../components/chart-config/generate/ChartGenerateConfig.vue')['default']
    ChartLegendConfig: typeof import('./../components/chart-config/legend/ChartLegendConfig.vue')['default']
    ChartMap3dConfig: typeof import('./../components/chart-config/map3d/ChartMap3dConfig.vue')['default']
    ChartPieConfig: typeof import('./../components/chart-config/pie/ChartPieConfig.vue')['default']
    ChartPolarConfig: typeof import('./../components/chart-config/polar/ChartPolarConfig.vue')['default']
    ChartRadiusAxisConfig: typeof import('./../components/chart-config/radius-axis/ChartRadiusAxisConfig.vue')['default']
    ChartRichTextConfig: typeof import('./../components/chart-config/label/ChartRichTextConfig.vue')['default']
    ChartSymbolConfig: typeof import('./../components/chart-config/symbol/ChartSymbolConfig.vue')['default']
    ChartTitleConfig: typeof import('./../components/chart-config/title/ChartTitleConfig.vue')['default']
    ChartTooltipConfig: typeof import('./../components/chart-config/tooltip/ChartTooltipConfig.vue')['default']
    ChartYxisConfig: typeof import('./../components/chart-config/yAxis/ChartYxisConfig.vue')['default']
    GBorderConfig: typeof import('./../components/ui/global-config/GBorderConfig.vue')['default']
    GCarousel: typeof import('./../components/ui/global-config/GCarousel.vue')['default']
    GChartAxislabelConfig: typeof import('./../components/ui/global-config/GChartAxislabelConfig.vue')['default']
    GChartAxisLineConfig: typeof import('./../components/ui/global-config/GChartAxisLineConfig.vue')['default']
    GChartAxistickConfig: typeof import('./../components/ui/global-config/GChartAxistickConfig.vue')['default']
    GChartDecalConfig: typeof import('./../components/ui/global-config/GChartDecalConfig.vue')['default']
    GChartFontConfig: typeof import('./../components/ui/global-config/GChartFontConfig.vue')['default']
    GChartGridConfig: typeof import('./../components/ui/global-config/GChartGridConfig.vue')['default']
    GChartItemConfig: typeof import('./../components/ui/global-config/GChartItemConfig.vue')['default']
    GChartLabelConfig: typeof import('./../components/ui/global-config/GChartLabelConfig.vue')['default']
    GChartLineAreaConfig: typeof import('./../components/ui/global-config/GChartLineAreaConfig.vue')['default']
    GChartLineConfig: typeof import('./../components/ui/global-config/GChartLineConfig.vue')['default']
    GChartShadowConfig: typeof import('./../components/ui/global-config/GChartShadowConfig.vue')['default']
    GChartSplitlineConfig: typeof import('./../components/ui/global-config/GChartSplitlineConfig.vue')['default']
    GlCarousel: typeof import('./../components/global/GlCarousel.vue')['default']
    GlChart: typeof import('./../components/global/GlChart.vue')['default']
    GlCountTo: typeof import('./../components/global/GlCountTo.vue')['default']
    GlIconPicker: typeof import('./../components/global/GlIconPicker.vue')['default']
    GlMapArea: typeof import('./../components/global/GlMapArea.vue')['default']
    GlMarSMap: typeof import('./../components/global/GlMarSMap.vue')['default']
    GlNumberAnimation: typeof import('./../components/global/GlNumberAnimation.vue')['default']
    GlNumberAnimationConfig: typeof import('./../components/chart-config/animation/GlNumberAnimationConfig.vue')['default']
    GlSelectCard: typeof import('./../components/global/GlSelectCard.vue')['default']
    GlSwiper: typeof import('./../components/global/GlSwiper.vue')['default']
    GlThreeMap: typeof import('./../components/global/three-map/GlThreeMap.vue')['default']
    GSwiperConfig: typeof import('./../components/ui/global-config/GSwiperConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
